### PR TITLE
fix: Add reverse prop

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
idk, i feel like `<Layout reverse>` looks nicer than `<Layout direction="row-reverse">`, and that's how we're mostly using it (in fact we don't even have a `column-reverse` style defined downstream)

wdyt?

**Review by jquense — APPROVED** [review]

**Comment by taion** [comment]
hmm should i tag this as `fix:` actually? to avoid the minor version bump?

**Comment by jquense** [comment]
sure 👍

**Pull request merged**
